# -*- coding: utf-8 -*-
import scrapy

from ..items import KnigaplusItem

class KnigSpider(scrapy.Spider):
    name = 'knig'
    start_urls = [
        'https://knigaplus.ru/katalog/books/antiques/?filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=12&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=13&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=14&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=15&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=16&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=17&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=18&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=19&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=20&filter_available=available',
        'https://knigaplus.ru/katalog/books/antiques/?p=21&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=12&filter_available=available',
        'https://knigaplus.ru/katalog/books/memuary/?p=13&filter_available=available',
        'https://knigaplus.ru/katalog/books/military/?filter_available=available',
        'https://knigaplus.ru/katalog/books/military/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/military/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/military/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/military/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/detskaya_literatura/?filter_available=available',
        'https://knigaplus.ru/katalog/books/kraevedenie/?filter_available=available',
        'https://knigaplus.ru/katalog/books/kraevedenie/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/kraevedenie/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/kraevedenie/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/kraevedenie/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=12&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=13&filter_available=available',
        'https://knigaplus.ru/katalog/books/iskusstvo/?p=14&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=12&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=13&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=14&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=15&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=16&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=17&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=18&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=19&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=20&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=21&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=22&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=23&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=24&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=25&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=26&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=27&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=28&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=29&filter_available=available',
        'https://knigaplus.ru/katalog/books/history/?p=30&filter_available=available',
        'https://knigaplus.ru/katalog/books/medicina/?filter_available=available',
        'https://knigaplus.ru/katalog/books/hobby/?filter_available=available',
        'https://knigaplus.ru/katalog/books/hobby/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/hobby/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/hobby/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/nauka/?filter_available=available',
        'https://knigaplus.ru/katalog/books/nauka/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=12&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=13&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=14&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=15&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=16&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=17&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=18&filter_available=available',
        'https://knigaplus.ru/katalog/books/obwestvennye_gymanitarny/?p=19&filter_available=available',
        'https://knigaplus.ru/katalog/books/strany_kontinenty/?filter_available=available',
        'https://knigaplus.ru/katalog/books/strany_kontinenty/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/strany_kontinenty/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/strany_kontinenty/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/strany_kontinenty/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/psihology/?filter_available=available',
        'https://knigaplus.ru/katalog/books/psihology/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/psihology/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/promyshlennost/?filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/religion/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/russkoyazychnye_zarubezhnye_izdaniya/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/uchebnaya_literatura/?filter_available=available',
        'https://knigaplus.ru/katalog/books/uchebnaya_literatura/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/philosophy/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=4&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=5&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=6&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=7&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=8&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=9&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=10&filter_available=available',
        'https://knigaplus.ru/katalog/books/hudozhestvennaya/?p=11&filter_available=available',
        'https://knigaplus.ru/katalog/books/yazykoznanie/?filter_available=available',
        'https://knigaplus.ru/katalog/books/yazykoznanie/?p=1&filter_available=available',
        'https://knigaplus.ru/katalog/books/yazykoznanie/?p=2&filter_available=available',
        'https://knigaplus.ru/katalog/books/yazykoznanie/?p=3&filter_available=available',
        'https://knigaplus.ru/katalog/books/yazykoznanie/?p=4&filter_available=available'
    
    ]

    def parse(self, response):
        knigi_uri = 'https://knigaplus.ru/'

        for knig in response.css('.b-good'):
            yield{
                'Url': knigi_uri + knig.css('a.b-good_pic_capsule::attr(href)').get(),
                'Name': knig.css('div.b-good_title a::text').get(),
                'Author': knig.css('p.b-good_author a::text').get(),
                'Price': knig.css('div.b-good_purchase_price strong::text').get(),
                'img_book': knigi_uri + knig.css('a.b-good_pic_capsule img::attr(data-src)').get()
            }

    # scrapy crawl knig